# -*- coding: utf-8 -*-
import io, sys, json
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8")
d = json.load(open("cases1980_full.json", encoding="utf-8"))
ch = d["chart"]; b1 = d["blind_L1"]; l2 = d["L2"]; t5 = d["L2_5"]
CN = {"GENGSHEN":"庚申","RENWU":"壬午","BINGYIN":"丙寅","GUISI":"癸巳"}
L = []
L.append("# 1980-06-22 10:00 男 广州 — 全链路引擎输出（L0→L2.5，停 L3 前）")
L.append("")
L.append("> 口径：八字排盘引擎（北京时间口径，compute 无地点参数）→ 盲派引擎（method_scope=DUAN_JIANYE）→ L2 解层 → L2.5 12主题。以下为引擎原始输出转 MD，无 LLM 参与断言。")
L.append("")
L.append("## 一、八字排盘 L0")
L.append("")
L.append("| 项 | 值 |")
L.append("|---|---|")
L.append(f"| 公历 | 1980-06-22 10:00 |")
L.append(f"| 性别 | 男 |")
L.append(f"| 年柱 | {CN.get(ch['year'],ch['year'])}（纳音：{ch['nayin']['year']}） |")
L.append(f"| 月柱 | {CN.get(ch['month'],ch['month'])}（纳音：{ch['nayin']['month']}） |")
L.append(f"| 日柱 | {CN.get(ch['day'],ch['day'])}（纳音：{ch['nayin']['day']}） |")
L.append(f"| 时柱 | {CN.get(ch['hour'],ch['hour'])}（纳音：{ch['nayin']['hour']}） |")
L.append(f"| 日主 | {ch['day_master']} |")
L.append("")
L.append("## 二、盲派 L1 结构/做功层")
L.append("")
L.append("### 宾主结构")
L.append("")
L.append(f"- 主位支：{b1['main_branches']}")
L.append(f"- 宾位支：{b1['guest_branches']}")
L.append(f"- 做功组（ti）：{b1['ti_branches']}")
L.append(f"- 目标组（yong）：{b1['yong_branches']}")
L.append(f"- 透干十神：年={b1['transparent_ten_gods']['year']} 月={b1['transparent_ten_gods']['month']} 时={b1['transparent_ten_gods']['hour']}")
L.append("")
L.append("### 做功方法（zuo_gong）")
L.append("")
L.append("| # | 方法 | 归属 | 明细 |")
L.append("|---|---|---|---|")
for i, (m, a, det) in enumerate(zip(b1["zuo_gong_methods"], b1["zuo_gong_attributions"], b1["zuo_gong_detail"])):
    L.append(f"| {i} | {m} | {a} | {det} |")
L.append("")
L.append("### 总判")
L.append("")
L.append(f"- 做功效率：{b1['work_efficiency']} | 制净：{b1['control_completeness']} | 做功等级：{b1['work_level']}")
L.append(f"- 做功类型串：{b1['zuo_gong_type']}")
L.append(f"- 顺逆反局：{b1['zheng_fan_ju']}（{b1['zheng_fan_ju_detail']}）")
L.append(f"- 盲派旺衰：{b1['blind_wangshuai']} | 盗气/换象：{b1['thief_capture']} | 干支传递：{b1['ganzhi_transmission']}")
L.append(f"- 六亲计数：{b1['kinship_chain']}")
L.append("")
L.append("## 三、L2 解层事件")
L.append("")
for e in l2["event_candidates"]:
    L.append(f"### {e['domain']} → {e['event_type']}（{e['direction']}）{e['status']}")
    L.append("")
    L.append(f"- 结构依据：{e['structure_ref']}")
    L.append(f"- 规则：{','.join(e['matched_rule_ids'])} | 证据：{','.join(e['evidence_refs'])} | 流派：{e['method_scope']}")
    if e.get("detail"):
        L.append(f"- 详情：{e['detail']}")
    L.append("")
L.append("## 四、L2.5 十二主题聚合")
L.append("")
L.append("| 主题 | 状态 | 引擎条目 |")
L.append("|---|---|---|")
for t in t5["themes"]:
    vals = "; ".join(f"{e['source']}={e['value']}" for e in t["entries"])
    L.append(f"| {t['theme_id']} {t['theme_name']} | {t['state']} | {vals} |")
L.append("")
io.open("cases1980_full.md", "w", encoding="utf-8").write("\n".join(L))
print("OK cases1980_full.md")
