# -*- coding: utf-8 -*-
"""用神层为什么不准——诚实审计"""
print('=== 用神层准确性审计 ===')
print()
print('【已验证的层】')
print('  L1结构层: 10万随机对拍0差异 ✅')
print('  L2旺衰层: 自己的规则自己全绿 ✅')
print('  L3格局层: 67 golden, 裸FAIL=0 ✅')
print()
print('【未验证的层】')
print('  L4用神层: 刚跑通, 0验证 ❌')
print()
print('【不准的原因】')
print('  1. 三路候选(扶抑/调候/病药)权重未钉')
print('  2. 位阶裁决(调候>病药>扶抑)未验证')
print('  3. 无golden例盘对照')
print()
print('【结论】')
print('  现在的用神输出 = 初版草稿')
print('  准确度 = 未知')
print('  要准 → 需: 六经例盘抠录 + 人工独立判 + 对拍')
