# -*- coding: utf-8 -*-
"""继续判盘2~10"""
print('盘2: 金状元 乙卯 丁亥 丁未 庚戌')
print('  ①月令定格: 亥月藏壬甲')
print('    本气壬透? 无')
print('    甲透? 是(年干乙? 不对, 乙是木)')
print('    丁日主, 壬是正官→无壬透')
print('    → 原文: 伤官格(未戌伤官)')
print('    → 判: 伤官格')
print()
print('  ②旺衰: 丁火日主')
print('    得令? 亥月水旺火绝→失令')
print('    得地? 未戌藏丁→得地')
print('    得势? 乙卯印生→印生')
print('    → 身弱')
print()
print('  ③用神: 乙卯印(制伤护官)')
print()
print('  ④成败: 伤官格')
print('    救应: 印星制伤')
print('    乙卯印透→成格')
print('    原文: 印制伤护官→成格')
print('    → 判: 成格')
print()
print('  ⑤刑冲: 无明显冲')
print()
print('  ⑥调候: 亥月丁火, 调候甲木')
print('    乙卯即调候→调候有')
print()
print('  【期望】')
print('    格局: 伤官格')
print('    成败: 成格(印制伤)')
print('    调候: 有')
print()
print('-'*60)
print()

print('盘6: 曲直格 甲寅 丁卯 乙卯 庚辰')
print('  ①月令定格: 卯月藏乙')
print('    本气乙透? 是(日主乙)→比劫不取格')
print('    → 走第二轮专旺')
print('    地支寅卯辰全→木方局')
print('    金透? 庚透(时干)→破格?')
print('    原文: 支全寅卯辰, 木旺成曲直')
print('    庚透但无根? 辰中乙余气→庚无根')
print('    → 不破, 曲直成格')
print()
print('  ②旺衰: 乙木日主, 木方局全→极旺')
print()
print('  ③用神: 顺势(木旺无金破)')
print()
print('  ④成败: 曲直格')
print('    破格物: 金')
print('    庚透但无根→不破')
print('    → 成格')
print()
print('  ⑤刑冲: 无')
print()
print('  ⑥调候: 卯月乙木, 调候丙癸')
print('    丙透? 丁是火, 丙是阳火→丁不是丙')
print('    → 调候缺(挂验)')
print()
print('  【期望】')
print('    格局: 曲直格')
print('    成败: 成格')
print('    调候: 缺')
print()
print('-'*60)
