# -*- coding: utf-8 -*-
"""盲派 Judgment Clause Condition Mapper V1 — 把Clause的condition_expr映射到实际Assertion特征。

问题：V1 Engine是"所有assertion_inputs命中即所有Clause满足"——这不对。
本模块把每个Clause的condition_expr映射到具体的布尔条件。

注意：V1只做"特征存在性"映射，不做复杂逻辑表达式。
真正的逻辑求值在V2中扩展。
"""

from __future__ import annotations

from typing import Dict, Set, Tuple


# ── Clause Condition 映射表 ───────────────────────────────────────
# 格式: (judgment_id, clause_id) → 所需额外特征条件
# 特征来源：从Assertion的subject/relation/object中提取

# 特征类别：
# FEAT_ROOT_IN_MAIN: 财根在主位
# FEAT_ROOT_IN_GUEST: 财根在宾位
# FEAT_WEALTH_AT_YEAR: 财在年柱
# FEAT_FANJU_AT_WEALTH: 反局在财位
# FEAT_OFFICIAL_AT_YEAR: 官在年柱
# FEAT_OFFICIAL_AT_DAY_HOUR: 官在日时
# FEAT_OFFICIAL_TRANSPARENT_ATTACK: 官透干克身
# FEAT_WEALTH_SOURCE_AT_BANK: 财原神=银行
# FEAT_CHEN_GONG_WATER: 辰拱水
# FEAT_NATAL_FANJU: 原局反局
# FEAT_LUCK_FANJU: 大运反局
# FEAT_YEAR_FANJU: 流年反局
# FEAT_STEM_LUCK_BRANCH_TI: 走干运支为体
# FEAT_BRANCH_LUCK_STEM_TI: 走支运干为体
# FEAT_NATAL_FANJU_CHEN: 原局反局+辰
# FEAT_HOUR_PILLAR_CHUAN: 时柱被穿
# FEAT_CHOU_YOU_YIN_RUMU: 丑酉阴中阴入墓
# FEAT_WOOD_FIRE_WEN: 木火=文
# FEAT_METAL_WATER_LI: 金水=理
# FEAT_XU_HAI_MATH: 戌亥=数学
# FEAT_CHOU_XUANXUE: 丑=玄学
# FEAT_SHEN_FINANCE_YOU_LAW: 申=金融酉=法律
# FEAT_YANG_WOOD_FIRE_FURNITURE: 阳木遇火=家具
# FEAT_YIN_WOOD_FIRE_TEXTILE: 阴木遇火=纺织
# FEAT_XIN_METAL_WEALTH_HARDWARE: 辛金取财=五金
# FEAT_FIRE_ATTACK_METAL_SMELTING: 火克金=冶炼
# FEAT_JIA_DING_HAIR_THIN: 甲丁=头发稀
# FEAT_JIA_HEAD_DING_FACE_GUI_ATTACK: 甲头丁面癸克=面损
# FEAT_LU_NO_YIN_HARD: 禄不配印=辛苦
# FEAT_LU_WITH_YIN_EASE: 禄配印=享受
# FEAT_YANGREN_CONTROLLED_ORTHODOX: 羊刃有制=正业
# FEAT_YANGREN_UNCONTROLLED_UNORTHODOX: 羊刃无制=偏业
# FEAT_YANGREN_MUKU_MILITARY: 羊刃库=军队
# FEAT_SHANGSHI_MUKU_SCHOOL: 伤食库=学校
# FEAT_WEALTH_MUKU_BANK: 财库=银行
# FEAT_GUANSHA_MUKU_ORG: 官杀库=组织
# FEAT_YIMA_PRESENT: 驿马存在
# FEAT_YIMA_HE_STATIONARY: 驿马被合
# FEAT_YEAR_KONGWANG_ZUYE: 年空亡=祖业空
# FEAT_MONTH_KONGWANG_BROTHER: 月空亡=兄弟无靠
# FEAT_DAY_KONGWANG_SPOUSE: 日空亡=夫妻缘薄
# FEAT_HOUR_KONGWANG_CHILDREN: 时空亡=子女迟育
# FEAT_FEMALE_LU_HE_TAOHUA: 女命禄合桃花
# FEAT_HOUR_BRANCH_SHENG_CAR: 时支被生=买车
# FEAT_HOUR_BRANCH_BREAK_CAR_RISK: 时支被破=车损
# FEAT_YEAR_BREAK_BY_MAIN_BIJIE: 年被主位比劫破
# FEAT_YEAR_RELATED_SPOUSE_PALACE: 年与妻宫关联
# FEAT_SPOUSE_AT_MONTH_SCHOOLMATE: 夫妻象在月=同学
# FEAT_WEALTH_STRONG_YEAR_MONTH_FEMALE: 年月财旺女命
# FEAT_WEALTH_TRANSPARENT_TALENT: 财虚透=才华
# FEAT_WEALTH_TRANSPARENT_AT_HOUR_FASHION: 财虚透时上=时尚
# FEAT_MALE_SHA_WITH_WEALTH_SON: 男杀有财=儿
# FEAT_MALE_SHA_NO_WEALTH_DAUGHTER: 男杀无财=女
# FEAT_CHUAN_WEALTH_DAUGHTER: 穿财=生女
# FEAT_HURT_OFFICIAL_LUCK_SON: 伤官运=生儿
# FEAT_SHISHEN_CHUAN_NO_SALVATION: 食神被穿无救
# FEAT_HOUR_PILLAR_CHUAN_CAR_THEFT: 时柱被穿=车盗
# FEAT_YANG_ATTACK_YIN_POLICE: 阳制阴=公安
# FEAT_WEALTH_WITH_OFFICIAL_CAP_PUBLIC: 财带官帽=公家
# FEAT_OFFICIAL_WITH_WEALTH_CAP_MANAGER: 官带财帽=管理
# FEAT_YIN_WITH_OFFICIAL_CAP_POWER: 印带官帽=权力
# FEAT_YIN_WITH_WEALTH_CAP_SALARY: 印带财帽=薪水
# FEAT_SHA_INTO_YANGREN_MUKU_MILITARY: 杀入羊刃墓=军队
# FEAT_CHEN_ZI_CHEMICAL_PHARMA: 辰子=化工制药
# FEAT_CHOU_WEI_CHONG_CAPITAL: 丑未冲=资本运营
# FEAT_LU_AS_WEALTH_CONDITION: 禄当财条件
# FEAT_LU_AS_WEALTH_YIN_SHENG: 禄当财印生禄
# FEAT_LU_WEALTH_HARD: 禄取财辛苦
# FEAT_LU_JIECAI_BROKEN: 禄见劫财破财
# FEAT_NO_WEALTH_SHANGSHI_AS_WEALTH: 无财伤食当财
# FEAT_SHANGSHI_WEALTH_NATURE: 伤食财性质
# FEAT_SHISHEN_STEM_BRANCH_NATURE: 食干支性质
# FEAT_GUAN_WEALTH_UNIFIED: 官统财/财统官
# FEAT_GUANSHA_NOT_CONTROLLED_PURE: 官杀制不净
# FEAT_INNER_SHISHEN_BUSINESS: 内食神=企业
# FEAT_SHISHEN_WITH_OFFICIAL_MANAGER: 食带官=经理人
# FEAT_WEALTH_AT_YEAR_REMOTE_TRADE: 财在年远方贸易
# FEAT_SPOUSE_PALACE_QUIET_CONTROL: 夫妻宫安静制星
# FEAT_SPOUSE_PALACE_DAMAGED: 夫妻宫被破坏
# FEAT_DAMAGE_LIGHT_NO_DIVORCE: 破坏轻不离婚
# FEAT_DAMAGE_HEAVY_DIVORCE: 破坏重必离异
# FEAT_BIJIE_COMPETE_SPOUSE: 比劫争配偶
# FEAT_SPOUSE_HE_CHONG_MARRIAGE_TIMING: 冲合婚期
# FEAT_SPOUSE_RUMU_CHONG_MARRIAGE_TIMING: 冲墓婚期
# FEAT_BIJIE_WITH_HUSBAND_STAR_COMPETE: 比劫与夫星关系
# FEAT_CHOU_CHEN_HAI_DAMAGE_YANG_USEFUL: 丑辰亥坏阳用
# FEAT_WATER_METAL_SINK_PRISON: 水多金沉牢狱
# FEAT_XIAO_SHEN_DUO_SHISHEN_FREEDOM: 枭神夺食失自由
# FEAT_JIECAISHANGSHI_ATTACK_OFFICIAL_PRISON: 劫财伤官抗官杀牢狱
# FEAT_FANJU_WITH_CHOU_CHEN_MOST_PRISON: 反局+丑辰多数牢狱
# FEAT_DAY_MASTER_LU_RELEASE: 日主得禄出狱
# FEAT_DAY_MASTER_HE_CHONG_RELEASE: 日主合冲出狱
# FEAT_PRISON_MUKU_CHUAN_RELEASE: 冲穿库出狱
# FEAT_JIECAI_OFFICIAL_AT_MAIN_THIEF: 劫财官在主=小偷
# FEAT_SHANGSHI_RUMU_FREEDOM_LOSS: 伤食入墓失自由


# Clause → 特征映射
# 格式: (judgment_id, clause_id) → 所需特征集合
CLAUSE_FEATURE_MAP: Dict[Tuple[str, str], Set[str]] = {
    # J-WEALTH-003
    ("J-WEALTH-003", "C1"): {"FEAT_ROOT_IN_MAIN"},
    ("J-WEALTH-003", "C2"): {"FEAT_ROOT_IN_GUEST"},
    ("J-WEALTH-003", "C3"): {"FEAT_WEALTH_AT_YEAR"},
    # J-WEALTH-005
    ("J-WEALTH-005", "C1"): {"FEAT_FANJU_AT_WEALTH"},
    # J-OFFICIAL-002
    ("J-OFFICIAL-002", "C1"): {"FEAT_OFFICIAL_AT_YEAR"},
    ("J-OFFICIAL-002", "C2"): {"FEAT_OFFICIAL_AT_DAY_HOUR"},
    # J-OFFICIAL-003
    ("J-OFFICIAL-003", "C1"): {"FEAT_OFFICIAL_TRANSPARENT_ATTACK"},
    # J-CAREER-001
    ("J-CAREER-001", "C1"): {"FEAT_WEALTH_SOURCE_AT_BANK"},
    ("J-CAREER-001", "C2"): {"FEAT_CHEN_GONG_WATER"},
    # J-SPECIAL-001
    ("J-SPECIAL-001", "C1"): {"FEAT_NATAL_FANJU"},
    ("J-SPECIAL-001", "C2"): {"FEAT_LUCK_FANJU"},
    ("J-SPECIAL-001", "C3"): {"FEAT_YEAR_FANJU"},
    # J-TIMING-002
    ("J-TIMING-002", "C1"): {"FEAT_STEM_LUCK_BRANCH_TI"},
    ("J-TIMING-002", "C2"): {"FEAT_BRANCH_LUCK_STEM_TI"},
    # J-DISASTER-002
    ("J-DISASTER-002", "C1"): {"FEAT_NATAL_FANJU_CHEN"},
    # J-HEALTH-002
    ("J-HEALTH-002", "C1"): {"FEAT_HOUR_PILLAR_CHUAN"},
    # J-DISASTER-003
    ("J-DISASTER-003", "C1"): {"FEAT_CHOU_YOU_YIN_RUMU"},
    # J-CAREER-003
    ("J-CAREER-003", "C1"): {"FEAT_WOOD_FIRE_WEN"},
    ("J-CAREER-003", "C2"): {"FEAT_METAL_WATER_LI"},
    ("J-CAREER-003", "C3"): {"FEAT_XU_HAI_MATH"},
    ("J-CAREER-003", "C4"): {"FEAT_CHOU_XUANXUE"},
    ("J-CAREER-003", "C5"): {"FEAT_SHEN_FINANCE_YOU_LAW"},
    # J-CAREER-004
    ("J-CAREER-004", "C1"): {"FEAT_YANG_WOOD_FIRE_FURNITURE"},
    ("J-CAREER-004", "C2"): {"FEAT_YIN_WOOD_FIRE_TEXTILE"},
    ("J-CAREER-004", "C3"): {"FEAT_XIN_METAL_WEALTH_HARDWARE"},
    ("J-CAREER-004", "C4"): {"FEAT_FIRE_ATTACK_METAL_SMELTING"},
    # J-HEALTH-003
    ("J-HEALTH-003", "C1"): {"FEAT_JIA_DING_HAIR_THIN"},
    ("J-HEALTH-003", "C2"): {"FEAT_JIA_HEAD_DING_FACE_GUI_ATTACK"},
    # J-WEALTH-006
    ("J-WEALTH-006", "C1"): {"FEAT_LU_NO_YIN_HARD"},
    ("J-WEALTH-006", "C2"): {"FEAT_LU_WITH_YIN_EASE"},
    # J-OFFICIAL-004
    ("J-OFFICIAL-004", "C1"): {"FEAT_YANGREN_CONTROLLED_ORTHODOX"},
    ("J-OFFICIAL-004", "C2"): {"FEAT_YANGREN_UNCONTROLLED_UNORTHODOX"},
    # J-CAREER-002
    ("J-CAREER-002", "C1"): {"FEAT_YANGREN_MUKU_MILITARY"},
    ("J-CAREER-002", "C2"): {"FEAT_SHANGSHI_MUKU_SCHOOL"},
    ("J-CAREER-002", "C3"): {"FEAT_WEALTH_MUKU_BANK"},
    ("J-CAREER-002", "C4"): {"FEAT_GUANSHA_MUKU_ORG"},
    # J-TIMING-003
    ("J-TIMING-003", "C1"): {"FEAT_YIMA_PRESENT"},
    ("J-TIMING-003", "C2"): {"FEAT_YIMA_HE_STATIONARY"},
    # J-KIN-002
    ("J-KIN-002", "C1"): {"FEAT_YEAR_KONGWANG_ZUYE"},
    ("J-KIN-002", "C2"): {"FEAT_MONTH_KONGWANG_BROTHER"},
    ("J-KIN-002", "C3"): {"FEAT_DAY_KONGWANG_SPOUSE"},
    ("J-KIN-002", "C4"): {"FEAT_HOUR_KONGWANG_CHILDREN"},
    # J-MARRIAGE-002
    ("J-MARRIAGE-002", "C1"): {"FEAT_FEMALE_LU_HE_TAOHUA"},
    # J-WEALTH-007
    ("J-WEALTH-007", "C1"): {"FEAT_HOUR_BRANCH_SHENG_CAR"},
    ("J-WEALTH-007", "C2"): {"FEAT_HOUR_BRANCH_BREAK_CAR_RISK"},
    # J-HEALTH-005
    ("J-HEALTH-005", "C1"): {"FEAT_YEAR_BREAK_BY_MAIN_BIJIE"},
    # J-KIN-003
    ("J-KIN-003", "C1"): {"FEAT_YEAR_RELATED_SPOUSE_PALACE"},
    # J-MARRIAGE-003
    ("J-MARRIAGE-003", "C1"): {"FEAT_SPOUSE_AT_MONTH_SCHOOLMATE"},
    # J-WEALTH-008
    ("J-WEALTH-008", "C1"): {"FEAT_WEALTH_STRONG_YEAR_MONTH_FEMALE"},
    # J-WEALTH-009
    ("J-WEALTH-009", "C1"): {"FEAT_WEALTH_TRANSPARENT_TALENT"},
    ("J-WEALTH-009", "C2"): {"FEAT_WEALTH_TRANSPARENT_AT_HOUR_FASHION"},
    # J-CHILD-001
    ("J-CHILD-001", "C1"): {"FEAT_MALE_SHA_WITH_WEALTH_SON"},
    ("J-CHILD-001", "C2"): {"FEAT_MALE_SHA_NO_WEALTH_DAUGHTER"},
    ("J-CHILD-001", "C3"): {"FEAT_CHUAN_WEALTH_DAUGHTER"},
    ("J-CHILD-001", "C4"): {"FEAT_HURT_OFFICIAL_LUCK_SON"},
    # J-KIN-004
    ("J-KIN-004", "C1"): {"FEAT_SHISHEN_CHUAN_NO_SALVATION"},
    # J-WEALTH-010
    ("J-WEALTH-010", "C1"): {"FEAT_HOUR_PILLAR_CHUAN_CAR_THEFT"},
    # J-OFFICIAL-005
    ("J-OFFICIAL-005", "C1"): {"FEAT_YANG_ATTACK_YIN_POLICE"},
    # J-WEALTH-011
    ("J-WEALTH-011", "C1"): {"FEAT_WEALTH_WITH_OFFICIAL_CAP_PUBLIC"},
    ("J-WEALTH-011", "C2"): {"FEAT_OFFICIAL_WITH_WEALTH_CAP_MANAGER"},
    ("J-WEALTH-011", "C3"): {"FEAT_YIN_WITH_OFFICIAL_CAP_POWER"},
    ("J-WEALTH-011", "C4"): {"FEAT_YIN_WITH_WEALTH_CAP_SALARY"},
    # J-OFFICIAL-006
    ("J-OFFICIAL-006", "C1"): {"FEAT_SHA_INTO_YANGREN_MUKU_MILITARY"},
    # J-CAREER-005
    ("J-CAREER-005", "C1"): {"FEAT_CHEN_ZI_CHEMICAL_PHARMA"},
    # J-WEALTH-012
    ("J-WEALTH-012", "C1"): {"FEAT_CHOU_WEI_CHONG_CAPITAL"},
    # J-WEALTH-013
    ("J-WEALTH-013", "C1"): {"FEAT_LU_AS_WEALTH_CONDITION"},
    ("J-WEALTH-013", "C2"): {"FEAT_LU_AS_WEALTH_YIN_SHENG"},
    ("J-WEALTH-013", "C3"): {"FEAT_LU_WEALTH_HARD"},
    ("J-WEALTH-013", "C4"): {"FEAT_LU_JIECAI_BROKEN"},
    # J-WEALTH-014
    ("J-WEALTH-014", "C1"): {"FEAT_NO_WEALTH_SHANGSHI_AS_WEALTH"},
    ("J-WEALTH-014", "C2"): {"FEAT_SHANGSHI_WEALTH_NATURE"},
    ("J-WEALTH-014", "C3"): {"FEAT_SHISHEN_STEM_BRANCH_NATURE"},
    # J-WEALTH-015
    ("J-WEALTH-015", "C1"): {"FEAT_GUAN_WEALTH_UNIFIED"},
    ("J-WEALTH-015", "C2"): {"FEAT_GUANSHA_NOT_CONTROLLED_PURE"},
    # J-CAREER-006
    ("J-CAREER-006", "C1"): {"FEAT_INNER_SHISHEN_BUSINESS"},
    ("J-CAREER-006", "C2"): {"FEAT_SHISHEN_WITH_OFFICIAL_MANAGER"},
    # J-WEALTH-016
    ("J-WEALTH-016", "C1"): {"FEAT_WEALTH_AT_YEAR_REMOTE_TRADE"},
    # J-MARRIAGE-004
    ("J-MARRIAGE-004", "C1"): {"FEAT_SPOUSE_PALACE_QUIET_CONTROL"},
    # J-MARRIAGE-005
    ("J-MARRIAGE-005", "C1"): {"FEAT_SPOUSE_PALACE_DAMAGED"},
    ("J-MARRIAGE-005", "C2"): {"FEAT_DAMAGE_LIGHT_NO_DIVORCE"},
    ("J-MARRIAGE-005", "C3"): {"FEAT_DAMAGE_HEAVY_DIVORCE"},
    ("J-MARRIAGE-005", "C4"): {"FEAT_BIJIE_COMPETE_SPOUSE"},
    # J-MARRIAGE-006
    ("J-MARRIAGE-006", "C1"): {"FEAT_SPOUSE_HE_CHONG_MARRIAGE_TIMING"},
    ("J-MARRIAGE-006", "C2"): {"FEAT_SPOUSE_RUMU_CHONG_MARRIAGE_TIMING"},
    # J-MARRIAGE-007
    ("J-MARRIAGE-007", "C1"): {"FEAT_BIJIE_WITH_HUSBAND_STAR_COMPETE"},
    # J-DISASTER-004
    ("J-DISASTER-004", "A"): {"FEAT_CHOU_CHEN_HAI_DAMAGE_YANG_USEFUL"},
    ("J-DISASTER-004", "B"): {"FEAT_WATER_METAL_SINK_PRISON"},
    ("J-DISASTER-004", "C"): {"FEAT_XIAO_SHEN_DUO_SHISHEN_FREEDOM"},
    ("J-DISASTER-004", "D"): {"FEAT_JIECAISHANGSHI_ATTACK_OFFICIAL_PRISON"},
    ("J-DISASTER-004", "E"): {"FEAT_FANJU_WITH_CHOU_CHEN_MOST_PRISON"},
    # J-DISASTER-005
    ("J-DISASTER-005", "C1"): {"FEAT_DAY_MASTER_LU_RELEASE"},
    ("J-DISASTER-005", "C2"): {"FEAT_DAY_MASTER_HE_CHONG_RELEASE"},
    ("J-DISASTER-005", "C3"): {"FEAT_PRISON_MUKU_CHUAN_RELEASE"},
    # J-WEALTH-017
    ("J-WEALTH-017", "C1"): {"FEAT_JIECAI_OFFICIAL_AT_MAIN_THIEF"},
    # J-DISASTER-006
    ("J-DISASTER-006", "C1"): {"FEAT_SHANGSHI_RUMU_FREEDOM_LOSS"},
}


# Exclusion 映射：exclusion描述 → 阻断条件
# 格式: (judgment_id, exclusion_index) → 阻断特征集合
EXCLUSION_FEATURE_MAP: Dict[Tuple[str, int], Set[str]] = {
    # J-WEALTH-003: 不估财富金额 → 阻断特征: FEAT_WEALTH_LEVEL
    ("J-WEALTH-003", 0): {"FEAT_WEALTH_LEVEL"},
    # J-WEALTH-005: 不估具体金额 → 阻断特征: FEAT_WEALTH_AMOUNT
    ("J-WEALTH-005", 0): {"FEAT_WEALTH_AMOUNT"},
    # J-OFFICIAL-002: 不估官职级别 → 阻断特征: FEAT_OFFICIAL_RANK
    ("J-OFFICIAL-002", 0): {"FEAT_OFFICIAL_RANK"},
    # J-OFFICIAL-003: 不做官级别判断 → 阻断特征: FEAT_OFFICIAL_RANK
    ("J-OFFICIAL-003", 0): {"FEAT_OFFICIAL_RANK"},
    # J-CAREER-001: 不指定具体职业名 → 阻断特征: FEAT_SPECIFIC_JOB_NAME
    ("J-CAREER-001", 0): {"FEAT_SPECIFIC_JOB_NAME"},
    ("J-CAREER-001", 1): {"FEAT_GENERIC_MAPPING_EXPANSION"},
    # J-SPECIAL-001: 正局不自动推吉 → 阻断特征: FEAT_ZHENG_AUTO_AUSPICIOUS
    ("J-SPECIAL-001", 0): {"FEAT_ZHENG_AUTO_AUSPICIOUS"},
    ("J-SPECIAL-001", 1): {"FEAT_SPECIFIC_EVENT_FROM_FANJU"},
    # J-TIMING-002: 此体用与第02章不同 → 阻断特征: FEAT_TIYONG_CONFUSION
    ("J-TIMING-002", 0): {"FEAT_TIYONG_CONFUSION"},
    # J-DISASTER-002: 辰单独不等于牢狱 → 阻断特征: FEAT_CHEN_ALONE_PRISON
    ("J-DISASTER-002", 0): {"FEAT_CHEN_ALONE_PRISON"},
    ("J-DISASTER-002", 1): {"FEAT_NO_FANJU_STRUCTURE"},
    # J-HEALTH-002: 是风险信号不是确诊 → 阻断特征: FEAT_MEDICAL_DIAGNOSIS
    ("J-HEALTH-002", 0): {"FEAT_MEDICAL_DIAGNOSIS"},
    # J-DISASTER-003: 辛丑日主不成立 → 阻断特征: FEAT_XINCHOU_CLEAR
    ("J-DISASTER-003", 0): {"FEAT_XINCHOU_CLEAR"},
    ("J-DISASTER-003", 1): {"FEAT_DEFINITE_CRIME"},
    ("J-DISASTER-003", 2): {"FEAT_GENERALIZE_YINYIN"},
    # J-CAREER-003: 只给学科方向 → 阻断特征: FEAT_SPECIFIC_MAJOR
    ("J-CAREER-003", 0): {"FEAT_SPECIFIC_MAJOR"},
    # J-CAREER-004: 只给行业方向 → 阻断特征: FEAT_SPECIFIC_COMPANY
    ("J-CAREER-004", 0): {"FEAT_SPECIFIC_COMPANY"},
    # J-HEALTH-003: 是风险信号不是确诊 → 阻断特征: FEAT_MEDICAL_DIAGNOSIS
    ("J-HEALTH-003", 0): {"FEAT_MEDICAL_DIAGNOSIS"},
    # J-WEALTH-006: 不得演化成财富等级 → 阻断特征: FEAT_WEALTH_LEVEL
    ("J-WEALTH-006", 0): {"FEAT_WEALTH_LEVEL"},
    ("J-WEALTH-006", 1): {"FEAT_HEZI_YIN_TAOHUA"},
    # J-OFFICIAL-004: 军警/外科只能作类象 → 阻断特征: FEAT_DIRECT_JOB_LABEL
    ("J-OFFICIAL-004", 0): {"FEAT_ORTHODOX_UNORTHODOX_DIRECTION_ONLY"},
    ("J-OFFICIAL-004", 1): {"FEAT_DIRECT_JOB_LABEL"},
    # J-CAREER-002: 只给机构方向 → 阻断特征: FEAT_SPECIFIC_INSTITUTION
    ("J-CAREER-002", 0): {"FEAT_SPECIFIC_INSTITUTION"},
    ("J-CAREER-002", 1): {"FEAT_WEALTH_MUKU_AUTO_BANK"},
    # J-TIMING-003: 驿马≠必然搬家 → 阻断特征: FEAT_YIMA_MOVE_GUARANTEE
    ("J-TIMING-003", 0): {"FEAT_YIMA_MOVE_GUARANTEE"},
    ("J-TIMING-003", 1): {"FEAT_YIMA_ONLY_SYMBOL"},
    # J-KIN-002: 空亡≠必然事件 → 阻断特征: FEAT_KONGWANG_DEFINITE_EVENT
    ("J-KIN-002", 0): {"FEAT_KONGWANG_DEFINITE_EVENT"},
    ("J-KIN-002", 1): {"FEAT_KONGWANG_ONLY_SYMBOL"},
    # J-MARRIAGE-002: 合夫妻宫不算桃花 → 阻断特征: FEAT_HE_SPOUSE_PALACE_TAOHUA
    ("J-MARRIAGE-002", 0): {"FEAT_HE_SPOUSE_PALACE_TAOHUA"},
    # J-WEALTH-007: 是信号不是必然 → 阻断特征: FEAT_CAR_EVENT_GUARANTEE
    ("J-WEALTH-007", 0): {"FEAT_CAR_EVENT_GUARANTEE"},
    # J-HEALTH-005: 是风险信号不是确诊 → 阻断特征: FEAT_MEDICAL_DIAGNOSIS
    ("J-HEALTH-005", 0): {"FEAT_MAIN_BREAK_GUEST_REQUIRED"},
    ("J-HEALTH-005", 1): {"FEAT_MEDICAL_DIAGNOSIS"},
    # J-KIN-003: 与妻宫无关则伤可能是奶奶 → 阻断特征: FEAT_NO_SPOUSE_PALACE_RELATION
    ("J-KIN-003", 0): {"FEAT_NO_SPOUSE_PALACE_RELATION"},
    # J-MARRIAGE-003: 只给来源方向不必然 → 阻断特征: FEAT_SPOUSE_SOURCE_GUARANTEE
    ("J-MARRIAGE-003", 0): {"FEAT_SPOUSE_SOURCE_GUARANTEE"},
    # J-WEALTH-008: 不必然只是倾向 → 阻断特征: FEAT_DROPOUT_GUARANTEE
    ("J-WEALTH-008", 0): {"FEAT_DROPOUT_GUARANTEE"},
    # J-WEALTH-009: 是象不必然 → 阻断特征: FEAT_WEALTH_SYMBOL_GUARANTEE
    ("J-WEALTH-009", 0): {"FEAT_WEALTH_SYMBOL_GUARANTEE"},
    # J-CHILD-001: 只是倾向不是必然 → 阻断特征: FEAT_CHILD_GENDER_GUARANTEE
    ("J-CHILD-001", 0): {"FEAT_CHILD_GENDER_GUARANTEE"},
    # J-KIN-004: 是风险信号不是必然 → 阻断特征: FEAT_MOTHER_DEATH_GUARANTEE
    ("J-KIN-004", 0): {"FEAT_MOTHER_DEATH_GUARANTEE"},
    # J-WEALTH-010: 是风险信号不是必然 → 阻断特征: FEAT_CAR_THEFT_GUARANTEE
    ("J-WEALTH-010", 0): {"FEAT_CAR_THEFT_GUARANTEE"},
    # J-OFFICIAL-005: 只给部门方向不指定级别 → 阻断特征: FEAT_DEPARTMENT_RANK
    ("J-OFFICIAL-005", 0): {"FEAT_DEPARTMENT_RANK"},
    # J-WEALTH-011: 是象不必然 → 阻断特征: FEAT_WEALTH_NATURE_GUARANTEE
    ("J-WEALTH-011", 0): {"FEAT_WEALTH_NATURE_GUARANTEE"},
    # J-OFFICIAL-006: 不推具体级别 → 阻断特征: FEAT_SPECIFIC_RANK
    ("J-OFFICIAL-006", 0): {"FEAT_SPECIFIC_RANK"},
    ("J-OFFICIAL-006", 1): {"FEAT_SPECIFIC_UNIT"},
    # J-CAREER-005: 只给行业方向 → 阻断特征: FEAT_SPECIFIC_INDUSTRY
    ("J-CAREER-005", 0): {"FEAT_SPECIFIC_INDUSTRY"},
    # J-WEALTH-012: 不估金额 → 阻断特征: FEAT_WEALTH_AMOUNT
    ("J-WEALTH-012", 0): {"FEAT_WEALTH_AMOUNT"},
    # J-WEALTH-013: 不估金额 → 阻断特征: FEAT_WEALTH_AMOUNT
    ("J-WEALTH-013", 0): {"FEAT_WEALTH_AMOUNT"},
    # J-WEALTH-014: 有财时伤食是原神 → 阻断特征: FEAT_HAS_WEALTH_SHANGSHI_YUANSHEN
    ("J-WEALTH-014", 0): {"FEAT_HAS_WEALTH_SHANGSHI_YUANSHEN"},
    # J-WEALTH-015: 只论原局 → 阻断特征: FEAT_LUCK_APPEARANCE
    ("J-WEALTH-015", 0): {"FEAT_LUCK_APPEARANCE"},
    ("J-WEALTH-015", 1): {"FEAT_WEALTH_LEVEL"},
    # J-CAREER-006: 不指定具体行业 → 阻断特征: FEAT_SPECIFIC_INDUSTRY
    ("J-CAREER-006", 0): {"FEAT_SPECIFIC_INDUSTRY"},
    # J-WEALTH-016: 不单独推海外贸易 → 阻断特征: FEAT_SINGLE_OVERSEAS_TRADE
    ("J-WEALTH-016", 0): {"FEAT_SINGLE_OVERSEAS_TRADE"},
    ("J-WEALTH-016", 1): {"FEAT_INCOMPLETE_STRUCTURE"},
    # J-MARRIAGE-004: 制之不住=反为坏婚姻 → 阻断特征: FEAT_CONTROL_INSUFFICIENT
    ("J-MARRIAGE-004", 0): {"FEAT_CONTROL_INSUFFICIENT"},
    # J-MARRIAGE-005: 不必然离婚 → 阻断特征: FEAT_DIVORCE_GUARANTEE
    ("J-MARRIAGE-005", 0): {"FEAT_DIVORCE_GUARANTEE"},
    ("J-MARRIAGE-005", 1): {"FEAT_MATH_DAMAGE_SCORE"},
    # J-MARRIAGE-006: 是应期窗口不是事件坐实 → 阻断特征: FEAT_MARRIAGE_EVENT_GUARANTEE
    ("J-MARRIAGE-006", 0): {"FEAT_MARRIAGE_EVENT_GUARANTEE"},
    # J-MARRIAGE-007: 只是可能不是必然 → 阻断特征: FEAT_COMPETE_GUARANTEE
    ("J-MARRIAGE-007", 0): {"FEAT_COMPETE_GUARANTEE"},
    # J-DISASTER-004: 阳制阴不算 → 阻断特征: FEAT_YANG_CONTROL_YIN
    ("J-DISASTER-004", 0): {"FEAT_YANG_CONTROL_YIN"},
    ("J-DISASTER-004", 1): {"FEAT_MOST_NOT_DEFINITE"},
    ("J-DISASTER-004", 2): {"FEAT_SINGLE_BOOLEAN"},
    # J-DISASTER-005: 是应期窗口不是事件坐实 → 阻断特征: FEAT_RELEASE_EVENT_GUARANTEE
    ("J-DISASTER-005", 0): {"FEAT_RELEASE_EVENT_GUARANTEE"},
    # J-WEALTH-017: 是结构象不是必然犯罪 → 阻断特征: FEAT_CRIME_GUARANTEE
    ("J-WEALTH-017", 0): {"FEAT_CRIME_GUARANTEE"},
    # J-DISASTER-006: 是结构象不是必然坐牢 → 阻断特征: FEAT_PRISON_GUARANTEE
    ("J-DISASTER-006", 0): {"FEAT_PRISON_GUARANTEE"},
}


def evaluate_clause(judgment_id: str, clause_id: str,
                    features_present: Set[str]) -> bool:
    """评估单个Clause是否满足"""
    key = (judgment_id, clause_id)
    required = CLAUSE_FEATURE_MAP.get(key, set())
    if not required:
        # 没有映射的Clause，默认True（V1框架级）
        return True
    return required.issubset(features_present)


def evaluate_exclusion(judgment_id: str, exclusions: Tuple[str, ...],
                        features_present: Set[str]) -> Tuple[bool, str]:
    """评估Exclusion是否触发
    Returns: (blocked, reason)
    """
    for i, excl in enumerate(exclusions):
        key = (judgment_id, i)
        blocking_features = EXCLUSION_FEATURE_MAP.get(key, set())
        if blocking_features & features_present:
            return True, f"Exclusion[{i}]: {excl}"
    return False, ""


if __name__ == "__main__":
    # 演示：全特征场景
    all_features = set(CLAUSE_FEATURE_MAP.values())
    all_features = set().union(*all_features) if all_features else set()

    # 统计
    print(f"Clause映射总数: {len(CLAUSE_FEATURE_MAP)}")
    print(f"Exclusion映射总数: {len(EXCLUSION_FEATURE_MAP)}")
    print(f"总特征数: {len(all_features)}")

    # 测试：空特征
    print(f"\n空特征测试:")
    print(f"  evaluate_clause(J-WEALTH-003, C1, empty) = {evaluate_clause('J-WEALTH-003', 'C1', set())}")

    # 测试：全特征
    print(f"\n全特征测试:")
    print(f"  evaluate_clause(J-WEALTH-003, C1, all) = {evaluate_clause('J-WEALTH-003', 'C1', all_features)}")
